---

- name: Java JDK - Download binaries
  ansible.builtin.get_url:
    url: "{{ jdk.url }}"
    dest: "{{ jdk.dest }}"

- name: Java JDK - Unarchive downloaded file
  become: true
  ansible.builtin.unarchive:
    src: "{{ jdk.dest }}"
    dest: "{{ jdk.final_dest}}"
    remote_src: yes

- name: Java JDK - Create a symbolic link
  become: true
  ansible.builtin.file:
    src: "{{ jdk.final_dest}}/{{ jdk.bin_name }}"
    dest: "{{ jdk.sym_link }}"
    owner: root
    group: root
    state: link

- name: Java JDK - Set the JAVA_HOME in /etc/profile file
  become: true
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - 'export JAVA_HOME="/opt/java"'
    - 'export PATH=$PATH:$JAVA_HOME/bin'    
    
- name: Reload /etc/profile file
  shell:
    cmd: source /etc/profile