---

# - name: Install Gnome Extensions
#   ansible.builtin.dnf:
#     name: gnome-extensions-app
#     state: present

- name: Add shortcut for Gnome Terminal (1/4)
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.command: 
    argv: 
      - /usr/bin/gsettings
      - set
      - org.gnome.settings-daemon.plugins.media-keys 
      - custom-keybindings 
      - '["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/"]'

- name: Add shortcut for Gnome Terminal (2/4)
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.command: 
    argv: 
      - /usr/bin/gsettings
      - set
      - org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ 
      - name 
      - 'Gnome Terminal'

- name: Add shortcut for Gnome Terminal (3/4)
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.command: 
    argv: 
      - /usr/bin/gsettings
      - set
      - org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ 
      - command 
      - 'gnome-terminal'

- name: Add shortcut for Gnome Terminal (4/4)
  become: true
  become_user: "{{ my_user }}"
  ansible.builtin.command: 
    argv: 
      - /usr/bin/gsettings
      - set
      - org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ 
      - binding 
      - '<Control><Alt>t'