---

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install common packages for Linux (utilities...)
  become: true
  ansible.builtin.dnf:
    name: "{{ common.packages}}"
    state: latest

- name: Import RPMFusion free distribution-gpg-keys
  become: true
  ansible.builtin.rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ fedora_version }}"
    state: present

- name: Import RPMFusion non-free distribution-gpg-keys
  become: true
  ansible.builtin.rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_version }}"
    state: present

  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    state: present
