---

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install common packages for Linux (utilities...)
  become: true
  ansible.builtin.dnf:
    name: "{{ common.packages}}"
    state: latest
