--- 

- name: Fedora Playbook Initialization (Desktop)
  hosts: localhost

- import_playbook: ansible-common.yml
  tags: common

- name: Desktop specific configurations
  hosts: localhost
  tasks:
  - name: Install Desktop Wallpapers(1/1)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/Monterey-Wide.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'
  