---
- name: Laptop specific configurations
  hosts: localhost
  tasks:

  - name: Install Desktop Wallpapers(1/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_01.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'

  - name: Install Desktop Wallpapers(2/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_02.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'

  - name: Install Desktop Wallpapers(3/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_03.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'