---
 
- name: Fedora Common Playbook
  hosts: localhost
  roles:

    # - role: common
    #   become: true
    #   tags: common
    
    # - role: flameshot
    #   become: true
    #   tags: flameshot

    # - role: fedy
    #   become: true
    #   tags: fedy

    # - role: gimp
    #   become: true
    #   tags: gimp
    
    # - role: inkscape
    #   become: true

    # - role: keepassxc
    #   become: true

    # - role: nextcloud
    #   become: false

    # - role: printing
    #   become: true

    # - role: element
    #   become: true

    # - role: vim
    #   become: true

    # - role: gnome
    #   become: true

    - role: terminal
      become: true

    # - role: r
    #   become: true


    # - role: appimagelauncher
    #   become: false
    #   tags: appimagelauncher

    # - role: vscode
    #   become: true

    # - role: fonts
    #   become: true