---
- name: Laptop specific configurations
  hosts: localhost
  tasks:

  - name: Install Desktop Wallpapers(1/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_01.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'

  - name: Install Desktop Wallpapers(2/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_02.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'

  - name: Install Desktop Wallpapers(3/3)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.copy:
      src: files/BigSurV2_03.jpg
      dest: "{{ my_home_folder }}/.local/share/backgrounds"
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: '0644'

  ## Tuxedo Drivers
  - name: Enable COPR for Tuxedo Drivers
    become: true
    community.general.copr:
      host: copr.fedorainfracloud.org
      name: kallepm/tuxedo-drivers
      state: enabled
  
  - name: Install Tuxedo Drivers
    become: true
    ansible.builtin.dnf:
      name: tuxedo-drivers
      state: present


  # Tuxedo Touchpad Switch
  - name: Enable COPR for Tuxedo Touchpad Switch
    become: true
    community.general.copr:
      host: copr.fedorainfracloud.org
      name: kallepm/tuxedo-touchpad-switch
      state: enabled
  
  - name: Install Tuxedo Touchpad Switch
    become: true
    ansible.builtin.dnf:
      name: tuxedo-touchpad-switch
      state: present


  # Tuxedo Control Center
  - name: Enable COPR for Tuxedo Control Center
    become: true
    community.general.copr:
      host: copr.fedorainfracloud.org
      name: kallepm/tuxedo-control-center
      state: enabled
  
  - name: Install Tuxedo Tuxedo Control Center
    become: true
    ansible.builtin.dnf:
      name: tuxedo-control-center
      state: present

  # Set Wallpapers
  - name: Set Wallpaper for Laptop (1/2)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.command: 
      argv: 
        - /usr/bin/gsettings
        - set
        - org.gnome.desktop.background 
        - picture-uri 
        - "'{{ my_home_folder }}/.local/share/backgrounds/BigSurV2_02.jpg'"
  
  - name: Set Wallpaper for Laptop (2/2)
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.command: 
      argv: 
        - /usr/bin/gsettings
        - set
        - org.gnome.desktop.background 
        - picture-options 
        - 'spanned'