---
- name: Fedora Playbook Initialization (Laptop)
  hosts: localhost

- import_playbook: ansible-common.yml
  tags: common
  
- import_playbook: ansible-customization.yml
  tags: custom

- name: Laptop specific configurations
  hosts: localhost
  tasks:

  - name: Add RPM Signing Key for Tuxedo Repository
    become: true
    ansible.builtin.rpm_key:
      key: "https://rpm.tuxedocomputers.com/fedora/40/0x54840598.pub.asc"
      state: present


  - name: Add repository for Tuxedo Software
    become: true
    ansible.builtin.yum_repository:
      name: tuxedo
      description: Tuxedo Computers
      baseurl: "https://rpm.tuxedocomputers.com/fedora/39/x86_64/base"
      gpgcheck: true
      gpgkey: "https://rpm.tuxedocomputers.com/fedora/39/0x54840598.pub.asc"
      enabled: true

  - name: Installing Tuxedo Control Center
    become: true
    ansible.builtin.dnf:
      name: tuxedo-control-center
      state: present

  # Set Scaling for HiDPI Screen
  - name: Enable fractional scaling of graph elements on Wayland
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.command:
      argv:
        - /usr/bin/gsettings
        - set 
        - org.gnome.mutter
        - experimental-features
        - "['scale-monitor-framebuffer']"

  # Enable tap to click in the login page
  - name: Enable tap to click in the GDM login screen
    become: true
    become_user: "{{ my_user }}"
    ansible.builtin.command:
      argv:
        - /usr/bin/gsettings
        - set 
        - org.gnome.desktop.peripherals.touchpad
        - tap-to-click
        - 'true'




  
