---
 
- name: Fedora Common Playbook
  hosts: localhost
  roles:

    - role: common
      become: true
      tags: common
    
    - role: flameshot
      become: true
      tags: flameshot

    - role: fedy
      become: true
      tags: fedy

    - role: gimp
      become: true
      tags: gimp
    
    - role: inkscape
      become: true

    - role: keepassxc
      become: true

    # - role: nextcloud
    #   become: false

    - role: printing
      become: true

    - role: element
      become: true

    - role: vim
      become: true

    - role: gnome
      become: true

    - role: terminal
      become: true

    # - role: r
    #  become: true
    #  tags: stat

    # - role: appimagelauncher
    #  become: false
    #  tags: general

    - role: vscode
      become: true
      tags: dev

    - role: fonts
      become: true
      tags: general

    # - role: pyenv
    #   tags: python-dev

    #- role: wine
    #  become: true
    #  tags: general

    - role: go
      tags: go

    - role: java-jdk
      become: true
      tags: java
