---

- name: Create directory for AppImages (if it not exists)
  become: false
  ansible.builtin.file:
    path: "{{appimage_dir}}"
    state: directory
    mode: '0755'


- name: Install AppImageD executable
  get_url:
    url: "{{appimaged.url}}"
    dest: /home/zaca/Applications/appimaged-x86_64.AppImage
    mode: '0755'

- name: Run appimaged
  command: /home/zaca/Applications/appimaged-x86_64.AppImage