---

- name: Install Fonts from Google
  become: true
  ansible.builtin.dnf:
    name: 'https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm'
    disable_gpg_check: true
    state: present
